# Generated by Django 5.2.12 on 2026-03-27 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Housing', 'Housing'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Investment', 'Investment'), ('Education', 'Education'), ('Shopping', 'Shopping'), ('Utilities', 'Utilities'), ('Other', 'Other')], default='Other', max_length=100)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
